spring:
  datasource:
    url: jdbc:mysql:///test?serverTimezone=UTC
    password: root
    username: root
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  thymeleaf:
    cache: false
  messages:
    encoding: UTF-8
    basename: message_zh_CN